"""Embed the current V10 INT8 model and contract into ESP-TRASH-V3."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from V10.config import (
    ARTIFACTS_DIR,
    CLASS_NAMES,
    ESP_V3_DIR,
    IMAGE_CHANNELS,
    IMAGE_HEIGHT,
    IMAGE_WIDTH,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifacts", type=Path, default=ARTIFACTS_DIR)
    parser.add_argument("--esp-dir", type=Path, default=ESP_V3_DIR)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    artifacts = args.artifacts.expanduser().resolve()
    esp_dir = args.esp_dir.expanduser().resolve()
    model_path = artifacts / "model_int8.tflite"
    quantization_path = artifacts / "quantization.json"
    metadata_path = artifacts / "model_metadata.json"
    if not esp_dir.is_dir():
        raise NotADirectoryError(esp_dir)
    model = model_path.read_bytes()
    quantization = json.loads(quantization_path.read_text(encoding="utf-8"))
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    digest = hashlib.sha256(model).hexdigest()
    if digest != quantization["sha256"] or digest != metadata["int8_model"]["sha256"]:
        raise RuntimeError("V10 model hashes disagree before embedding")
    if metadata["labels"] != list(CLASS_NAMES):
        raise RuntimeError("V10 metadata label order is invalid")

    (esp_dir / "model_data.cpp").write_text(
        _render_model_data(model, digest), encoding="utf-8", newline="\n"
    )
    (esp_dir / "model_contract.h").write_text(
        _render_contract(model, digest, quantization), encoding="utf-8", newline="\n"
    )
    deployment = {
        "source_model": str(model_path),
        "model_version": metadata["model_version"],
        "bytes": len(model),
        "sha256": digest,
        "labels": list(CLASS_NAMES),
        "input": quantization["input"],
        "output": quantization["output"],
        "operators": quantization["unique_operators"],
        "self_test": quantization["self_test"],
        "preprocessing": metadata["preprocessing"],
        "test_metrics": quantization["metrics"]["test"],
    }
    (esp_dir / "deployment_contract.json").write_text(
        json.dumps(deployment, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps({
        "embedded_into": str(esp_dir),
        "bytes": len(model),
        "sha256": digest,
        "self_test": quantization["self_test"],
    }, indent=2))


def _render_model_data(model: bytes, digest: str) -> str:
    lines = []
    for start in range(0, len(model), 12):
        chunk = ", ".join(f"0x{value:02x}" for value in model[start:start + 12])
        lines.append(f"    {chunk},")
    body = "\n".join(lines)
    return f'''#include "model_data.h"

#include <cstddef>

alignas(16) const unsigned char g_model[] = {{
{body}
}};

const int g_model_len = {len(model)};
const char g_model_sha256[65] = "{digest}";
'''


def _render_contract(model: bytes, digest: str, quantization: dict) -> str:
    input_quant = quantization["input"]["quantization"]
    output_quant = quantization["output"]["quantization"]
    self_test = quantization["self_test"]
    observed_margin = int(self_test["minimum_raw_margin"])
    required_margin = max(1, observed_margin // 2)
    labels = ", ".join(f'"{label}"' for label in CLASS_NAMES)
    class_enum = {0: "kPaper", 1: "kPlastic", 2: "kOrganic"}
    expected_enum = class_enum[int(self_test["expected_class_index"])]
    return f'''#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace aiot::model_contract {{

// Generated by AI/V10/embed_model.py. Keep synchronized with V10 artifacts.
inline constexpr int kInputBatch = 1;
inline constexpr int kInputHeight = {IMAGE_HEIGHT};
inline constexpr int kInputWidth = {IMAGE_WIDTH};
inline constexpr int kInputChannels = {IMAGE_CHANNELS};
inline constexpr int kClassCount = {len(CLASS_NAMES)};

inline constexpr float kExpectedInputScale = {float(input_quant['scale']):.12g}F;
inline constexpr std::int32_t kExpectedInputZeroPoint = {int(input_quant['zero_point'])};
inline constexpr float kExpectedOutputScale = {float(output_quant['scale']):.12g}F;
inline constexpr std::int32_t kExpectedOutputZeroPoint = {int(output_quant['zero_point'])};
inline constexpr float kQuantizationTolerance = 1.0e-7F;

inline constexpr int kExpectedModelBytes = {len(model)};
inline constexpr char kExpectedModelSha256[] =
    "{digest}";

enum class OutputSemantic : std::uint8_t {{
  kLogits,
  kProbabilities,
}};
inline constexpr OutputSemantic kOutputSemantic = OutputSemantic::kProbabilities;

enum class WasteClass : std::uint8_t {{
  kPaper = 0,
  kPlastic = 1,
  kOrganic = 2,
  kInvalid = 255,
}};

inline constexpr std::array<const char*, kClassCount> kLabels = {{{labels}}};

inline constexpr std::uint32_t kSelfTestMultiplier = {int(self_test['multiplier'])}U;
inline constexpr std::uint32_t kSelfTestOffset = {int(self_test['offset'])}U;
inline constexpr WasteClass kSelfTestExpectedClass = WasteClass::{expected_enum};
inline constexpr int kSelfTestMinimumRawMargin = {required_margin};

inline constexpr std::size_t kTensorArenaBytes = 256U * 1024U;

}}  // namespace aiot::model_contract
'''


if __name__ == "__main__":
    main()
