#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace aiot::model_contract {

// Generated by AI/V9/embed_model.py. Keep synchronized with V9 artifacts.
inline constexpr int kInputBatch = 1;
inline constexpr int kInputHeight = 96;
inline constexpr int kInputWidth = 96;
inline constexpr int kInputChannels = 3;
inline constexpr int kClassCount = 3;

inline constexpr float kExpectedInputScale = 0.00392156885937F;
inline constexpr std::int32_t kExpectedInputZeroPoint = -128;
inline constexpr float kExpectedOutputScale = 0.00390625F;
inline constexpr std::int32_t kExpectedOutputZeroPoint = -128;
inline constexpr float kQuantizationTolerance = 1.0e-7F;

inline constexpr int kExpectedModelBytes = 62560;
inline constexpr char kExpectedModelSha256[] =
    "851054bd0256a3173aa69a2dee733f059d14651271e684be06bc750cf8564253";

enum class OutputSemantic : std::uint8_t {
  kLogits,
  kProbabilities,
};
inline constexpr OutputSemantic kOutputSemantic = OutputSemantic::kProbabilities;

enum class WasteClass : std::uint8_t {
  kPaper = 0,
  kPlastic = 1,
  kOrganic = 2,
  kInvalid = 255,
};

inline constexpr std::array<const char*, kClassCount> kLabels = {"paper", "plastic", "organic"};

inline constexpr std::uint32_t kSelfTestMultiplier = 191U;
inline constexpr std::uint32_t kSelfTestOffset = 7U;
inline constexpr WasteClass kSelfTestExpectedClass = WasteClass::kOrganic;
inline constexpr int kSelfTestMinimumRawMargin = 127;

inline constexpr std::size_t kTensorArenaBytes = 256U * 1024U;

}  // namespace aiot::model_contract
